include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
scripts:
  format-code:
    exec: dart format . --line-length 120
    description: "Format Dart code for selected package"

  format-check:
    exec: dart format . --line-length 120 --set-exit-if-changed
    description: "Check format all Dart code"
