name: todos_api
description: The interface and models for an API providing access to todos.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

dependencies:
  equatable: ^2.0.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  uuid: ^3.0.6
  rxdart: ^0.28.0
  shared_preferences: ^2.0.0
